### ISSUE TITLE
In game music does not play (Ubuntu / Snap version)

### ISSUE THREAD

**Issue by jukey** [diddlesnaps/openttd#5]
This bug initially was reported at https://github.com/OpenTTD/OpenTTD/issues/8370

## Version of OpenTTD
snap-id:      vIoqO99N39KayGkEhJO4nW6o06tk5SYt
tracking:     latest/stable
version: 1.10.3 2020-12-10 (392) 95MB

I installed the game from the official Ubuntu App Store (using snaps) in Ubuntu 20.04.1 LTS.

## Steps to reproduce
1. Install the Game
2. Run the Game
3. Ensure that the OpenMSX is set in the Game Options
4. Start a game
5. Open the In Game Music Player
6. Press the play button of the player

## Expected result
Game Music is playing if started using the player within the game.

## Actual result
Music does not play and the in game player 'jumpes' from track to track multiple times a second.

**Comment by lucyllewy** [comment]
The fix for this is building and will be available shortly.

**Comment by jukey** [comment]
It's available now and works like a charm. Thanks for fixing! :-)
